/**
 * Auto-generated by `packages/lyrics/scripts/bundle-corpus.ts`. Do not
 * edit by hand. To regenerate after adding a lyric:
 *
 *   pnpm --filter @neo-fm/lyrics bundle:corpus
 *
 * The corpus is bundled (rather than loaded from disk at runtime) so the
 * Vercel-deployed web app can serve it without shipping the markdown
 * directory next to the function bundle. See
 * `packages/lyrics/scripts/bundle-corpus.ts` for the source-of-truth.
 *
 * Provenance enforcement still happens in CI via
 * `scripts/verify-lyrics-provenance.py`. This file is purely the data
 * mirror.
 */
import type { LyricsEntry } from "./corpus.js";

export const BUNDLED_CORPUS: readonly LyricsEntry[] = [
  {
    "id": "en/blake-tyger",
    "title": "The Tyger",
    "author": "William Blake",
    "language": "en",
    "script": "latin",
    "body": "Tyger Tyger, burning bright,\nIn the forests of the night;\nWhat immortal hand or eye,\nCould frame thy fearful symmetry?\n\nIn what distant deeps or skies,\nBurnt the fire of thine eyes?\nOn what wings dare he aspire?\nWhat the hand, dare seize the fire?\n\nAnd what shoulder, & what art,\nCould twist the sinews of thy heart?\nAnd when thy heart began to beat,\nWhat dread hand? & what dread feet?\n\nWhat the hammer? what the chain,\nIn what furnace was thy brain?\nWhat the anvil? what dread grasp,\nDare its deadly terrors clasp!\n\nWhen the stars threw down their spears\nAnd water'd heaven with their tears:\nDid he smile his work to see?\nDid he who made the Lamb make thee?\n\nTyger Tyger burning bright,\nIn the forests of the night:\nWhat immortal hand or eye,\nDare frame thy fearful symmetry?",
    "source_url": "https://www.gutenberg.org/files/1934/1934-h/1934-h.htm",
    "source_citation": "Songs of Innocence and of Experience (1794), Project Gutenberg eText 1934",
    "license_assertion": "public-domain"
  },
  {
    "id": "en/dickinson-hope",
    "title": "Hope is the Thing with Feathers",
    "author": "Emily Dickinson",
    "language": "en",
    "script": "latin",
    "body": "\"Hope\" is the thing with feathers—\nThat perches in the soul—\nAnd sings the tune without the words—\nAnd never stops—at all—\n\nAnd sweetest—in the Gale—is heard—\nAnd sore must be the storm—\nThat could abash the little Bird\nThat kept so many warm—\n\nI've heard it in the chillest land—\nAnd on the strangest Sea—\nYet, never, in Extremity,\nIt asked a crumb—of Me.",
    "source_url": "https://www.gutenberg.org/files/12242/12242-h/12242-h.htm",
    "source_citation": "Poems by Emily Dickinson, Second Series, ed. Higginson & Todd (1891), Project Gutenberg eText 12242",
    "license_assertion": "public-domain"
  },
  {
    "id": "en/whitman-song-of-myself-1",
    "title": "Song of Myself (Section 1)",
    "author": "Walt Whitman",
    "language": "en",
    "script": "latin",
    "body": "I celebrate myself, and sing myself,\nAnd what I assume you shall assume,\nFor every atom belonging to me as good belongs to you.\n\nI loafe and invite my soul,\nI lean and loafe at my ease observing a spear of summer grass.\n\nMy tongue, every atom of my blood, form'd from this soil, this air,\nBorn here of parents born here from parents the same, and their parents the same,\nI, now thirty-seven years old in perfect health begin,\nHoping to cease not till death.\n\nCreeds and schools in abeyance,\nRetiring back a while sufficed at what they are, but never forgotten,\nI harbor for good or bad, I permit to speak at every hazard,\nNature without check with original energy.",
    "source_url": "https://www.gutenberg.org/files/1322/1322-h/1322-h.htm",
    "source_citation": "Leaves of Grass, Deathbed Edition (1892), Project Gutenberg eText 1322",
    "license_assertion": "public-domain"
  },
  {
    "id": "en/wordsworth-daffodils",
    "title": "I Wandered Lonely as a Cloud",
    "author": "William Wordsworth",
    "language": "en",
    "script": "latin",
    "body": "I wandered lonely as a cloud\nThat floats on high o'er vales and hills,\nWhen all at once I saw a crowd,\nA host, of golden daffodils;\nBeside the lake, beneath the trees,\nFluttering and dancing in the breeze.\n\nContinuous as the stars that shine\nAnd twinkle on the milky way,\nThey stretched in never-ending line\nAlong the margin of a bay:\nTen thousand saw I at a glance,\nTossing their heads in sprightly dance.\n\nThe waves beside them danced; but they\nOut-did the sparkling waves in glee:\nA poet could not but be gay,\nIn such a jocund company:\nI gazed—and gazed—but little thought\nWhat wealth the show to me had brought.\n\nFor oft, when on my couch I lie\nIn vacant or in pensive mood,\nThey flash upon that inward eye\nWhich is the bliss of solitude;\nAnd then my heart with pleasure fills,\nAnd dances with the daffodils.",
    "source_url": "https://www.gutenberg.org/files/12145/12145-h/12145-h.htm",
    "source_citation": "Poems by William Wordsworth (1815 collected edition), Project Gutenberg eText 12145",
    "license_assertion": "public-domain"
  },
  {
    "id": "hi/kabir-pothi",
    "title": "Doha: Pothi Padhi Padhi Jag Mua",
    "author": "Kabir",
    "language": "hi",
    "script": "devanagari",
    "body": "पोथी पढ़ि पढ़ि जग मुआ, पंडित भया न कोय।\nढाई आखर प्रेम का, पढ़े सो पंडित होय॥\n\nबड़ा हुआ तो क्या हुआ, जैसे पेड़ खजूर।\nपंथी को छाया नहीं, फल लागे अति दूर॥",
    "source_url": "https://archive.org/details/in.ernet.dli.2015.396418",
    "source_citation": "Kabir Granthavali, ed. Shyam Sundar Das, Nagari Pracharini Sabha (1915), digitised in the Digital Library of India",
    "license_assertion": "public-domain"
  },
  {
    "id": "hi/mira-payoji-maine",
    "title": "Payoji Maine Ram Ratan Dhan Payo",
    "author": "Mirabai",
    "language": "hi",
    "script": "devanagari",
    "body": "पायो जी मैंने राम रतन धन पायो।\nवस्तु अमोलक दी मेरे सतगुरु, किरपा करि अपनायो॥\n\nजनम जनम की पूँजी पाई, जग में सभी खोवायो।\nखरचै नहिं कोई चोर न लूटै, दिन-दिन बढ़त सवायो॥\n\nसत की नाव, खेवटिया सतगुरु, भवसागर तर आयो।\nमीरा के प्रभु गिरिधर नागर, हरख-हरख जस गायो॥",
    "source_url": "https://archive.org/details/in.ernet.dli.2015.282671",
    "source_citation": "Mira Padavali, Nagari Pracharini Sabha edition (1920), digitised in the Digital Library of India",
    "license_assertion": "public-domain"
  },
  {
    "id": "hi/surdas-maiya-mori",
    "title": "Maiya Mori, Main Nahi Makhan Khayo",
    "author": "Surdas",
    "language": "hi",
    "script": "devanagari",
    "body": "मैया मोरी, मैं नहीं माखन खायो।\nख्याल परे ये सखा सबै मिलि, मेरे मुख लपटायो॥\n\nदेखि तुही छींके पर भाजन, ऊँचे धरि लटकायो।\nहौं जु कहत नान्हें कर अपने, मैं कैसे करि पायो॥\n\nमुख दधि पोंछि, बुद्धि इक कीन्ही, दौनी लै ज्योँ आयो।\nडारि साँटि मुसुकाइ जसोदा, स्यामहिं कंठ लगायो॥\n\nसूरदास तब बिहँसि जसोदा, ले उर कंठ लगायो।\nनिरगुन ब्रह्म अगम अगोचर, गोपिनि के बस आयो॥",
    "source_url": "https://archive.org/details/in.ernet.dli.2015.464810",
    "source_citation": "Sursagar, Nagari Pracharini Sabha edition (1910), digitised in the Digital Library of India",
    "license_assertion": "public-domain"
  },
  {
    "id": "hi/tulsidas-hanuman-chalisa-opening",
    "title": "Hanuman Chalisa: Opening Doha and First Chaupais",
    "author": "Tulsidas",
    "language": "hi",
    "script": "devanagari",
    "body": "श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि।\nबरनउँ रघुबर बिमल जसु, जो दायकु फल चारि॥\n\nबुद्धिहीन तनु जानिके, सुमिरौं पवनकुमार।\nबल बुद्धि बिद्या देहु मोहिं, हरहु कलेस बिकार॥\n\nजय हनुमान ज्ञान गुन सागर।\nजय कपीस तिहुँ लोक उजागर॥\nराम दूत अतुलित बल धामा।\nअंजनिपुत्र पवनसुत नामा॥",
    "source_url": "https://archive.org/details/in.ernet.dli.2015.282671",
    "source_citation": "Sri Tulsi Granthavali, Nagari Pracharini Sabha edition (1905), digitised in the Digital Library of India",
    "license_assertion": "public-domain"
  },
  {
    "id": "kn/akkamahadevi-vachana-elava",
    "title": "Vachana: Elava Yejjava Konaava",
    "author": "Akka Mahadevi",
    "language": "kn",
    "script": "kannada",
    "body": "ಎಳ್ಳವ ಯೆಜ್ಜವ ಕೋಣಾವ ಎನ್ನುತ್ತ।\nಬೆಳ್ಳಿಯ ಗುರಿಸಿಕೊಂಡು ಆಡುವ ಬಯಲಿಗೆ॥\n\nಚೆನ್ನಮಲ್ಲಿಕಾರ್ಜುನನ ಕಂಡು ಕೈಮುಗಿಯಲು।\nಕನ್ನಡಿಯೊಳಗಣ ರೂಪು ತೋರಿತು ಕಣಾ॥\n\nಒಲಿದು ಒಲ್ಲದೆ ನಿಂದಿರಲು ಬೇಡ।\nಬೆಳಗಿನ ಮನೆಯೊಳಗೆ ನಿಜವಾಗಿರು॥",
    "source_url": "https://archive.org/details/in.ernet.dli.2015.347510",
    "source_citation": "Akkamahadeviya Vachanagalu, Karnataka Granthamale (1923), digitised in the Digital Library of India",
    "license_assertion": "public-domain"
  },
  {
    "id": "kn/basavanna-vachana-kalabeda",
    "title": "Vachana: Kalabeda Kolabeda",
    "author": "Basavanna",
    "language": "kn",
    "script": "kannada",
    "body": "ಕಳಬೇಡ ಕೊಲಬೇಡ ಹುಸಿಯ ನುಡಿಯಲು ಬೇಡ।\nಮುನಿಯಬೇಡ ಅನ್ಯರಿಗೆ ಅಸಹ್ಯಪಡಬೇಡ॥\nತನ್ನ ಬಣ್ಣಿಸಬೇಡ ಇದಿರ ಹಳಿಯಲು ಬೇಡ।\nಇದೇ ಅಂತರಂಗ ಶುದ್ಧಿ ಇದೇ ಬಹಿರಂಗ ಶುದ್ಧಿ॥\nಇದೇ ನಮ್ಮ ಕೂಡಲಸಂಗಮದೇವರನೊಲಿಸುವ ಪರಿ॥",
    "source_url": "https://archive.org/details/in.ernet.dli.2015.349620",
    "source_citation": "Basavanna Vachanagalu, Karnataka Granthamale (1923), digitised in the Digital Library of India",
    "license_assertion": "public-domain"
  },
  {
    "id": "kn/kanakadasa-baagilanu",
    "title": "Baagilanu Teredu Seveyanu Kodu Hari",
    "author": "Kanaka Dasa",
    "language": "kn",
    "script": "kannada",
    "body": "ಬಾಗಿಲನು ತೆರೆದು ಸೇವೆಯನು ಕೊಡು ಹರಿಯೆ।\nಕೂಗಿದರು ಧ್ವನಿ ಕೇಳಿ ಬಂದು ಬೇಗದಲಿ ಎನಗೆ॥\n\nಬ್ರಹ್ಮಾದಿ ದೇವತೆಗಳಿಂದ ಕಾಣದ ರೂಪ।\nಸುಮ್ಮನೆ ಎನಗಿಂದು ಸುಲಭದಿ ಬರಲಿ ದೇವ॥\n\nತೆರೆಯೆಂದು ಕರೆದರೆ ಬಗೆಬಗೆ ಶಂಕೆಗಳು।\nಸುರರಾಜ ಶ್ರೀ ಆದಿ ಕೇಶವನೆ ಕರುಣಿಸಲಿ॥",
    "source_url": "https://archive.org/details/in.ernet.dli.2015.394989",
    "source_citation": "Kanakadasa Keertanegalu, Karnataka Granthamale (1918), digitised in the Digital Library of India",
    "license_assertion": "public-domain"
  },
  {
    "id": "kn/purandaradasa-jagadoddharana",
    "title": "Jagadoddharana Adisidale Yashode",
    "author": "Purandara Dasa",
    "language": "kn",
    "script": "kannada",
    "body": "ಜಗದೋದ್ಧಾರನ ಆಡಿಸಿದಳೆ ಯಶೋದ।\nಜಗದೋದ್ಧಾರನ ಮಗನೆಂದು ತಿಳಿಯುತ\nಸುಗುಣಾಂತರಂಗನ ಆಡಿಸಿದಳೆ ಯಶೋದ॥\n\nನಿಗಮಕೆ ಸಿಲುಕದ ಅಗಣಿತ ಮಹಿಮನ\nನಿಗಮಗೋಚರನ ಆಡಿಸಿದಳೆ ಯಶೋದ॥\n\nಅನಂತ ಅಪ್ರಮೇಯನ ಎನಿಪನು ಎಂಬ\nಬಿನಿತು ಚರಿತನ ಆಡಿಸಿದಳೆ ಯಶೋದ॥\n\nಪರಮ ಪುರುಷನ ಸಿರಿ ವರ ಪುರಂದರ ವಿಠಲನ\nನರಹರಿ ರೂಪನ ಆಡಿಸಿದಳೆ ಯಶೋದ॥",
    "source_url": "https://archive.org/details/in.ernet.dli.2015.394987",
    "source_citation": "Purandara Sahitya Darshana, Karnataka Granthamale (1912), digitised in the Digital Library of India",
    "license_assertion": "public-domain"
  }
] as const;

export function bundledCorpusForLanguage(language: LyricsEntry["language"]): LyricsEntry[] {
  return BUNDLED_CORPUS.filter((e) => e.language === language);
}

export function findBundledLyric(id: string): LyricsEntry | undefined {
  return BUNDLED_CORPUS.find((e) => e.id === id);
}
