/**
 * `PublicLyricsLibraryProvider` — Phase 3.
 *
 * Reads the public-domain corpus from disk, picks a matching entry, and
 * returns a validated `SongDocument` scaffold. The choice of entry is
 * deterministic so the Phase 3 demo and CI parity tests are reproducible:
 *
 *   - If `request.reference_lyrics` matches an entry id (`<lang>/<file>`) or a
 *     significant substring of an entry's title, that entry wins.
 *   - Otherwise the first alphabetically-sorted entry in the requested
 *     language wins.
 *
 * `PratyabhijnaProvider` continues to throw — it lives behind the feature
 * flag and lands properly in Phase 10. We keep the class here so cloud
 * routing code can wire it without referencing an unimplemented module.
 */

import {
  SongDocumentSchema,
  NotYetIntegratedError,
  allocateSectionDurations,
  type Duration,
  type Language,
  type SongDocument,
  type StyleFamily,
} from "@neo-fm/song-doc";

import { BUNDLED_CORPUS_LANGUAGES } from "./bundled-corpus.js";
import { loadCorpus, type LoadCorpusOptions, type LyricsEntry } from "./corpus.js";
import { mapToSections } from "./section-mapper.js";

export interface LyricsRequest {
  language: Language;
  style_family: StyleFamily;
  prompt?: string;
  reference_lyrics?: string;
  target_duration_seconds: Duration;
}

export interface LyricsProvider {
  readonly id: string;
  generate(request: LyricsRequest): Promise<SongDocument>;
}

export interface PublicLyricsLibraryProviderOptions {
  /** Filesystem path to `data/public-lyrics/`. Useful for tests. */
  rootDir?: string;
}

// v1.4 Sprint 6: which languages a style family will accept lyrics in.
// The set of "preferred" languages per style stays hand-curated (it
// encodes domain knowledge — Carnatic kritis are Telugu/Kannada/Sanskrit,
// not English). But the *runtime* allow-list is intersected with what's
// actually present on disk (BUNDLED_CORPUS_LANGUAGES, generated by
// scripts/bundle-corpus.ts), so adding new public-domain Tulsidas Hindi
// poems to a Carnatic raga set doesn't require code changes here — drop
// the markdown into `data/public-lyrics/hi/` and rerun bundle:corpus.
const STYLE_LANGUAGE_PREFERENCE: Record<StyleFamily, readonly Language[]> = {
  western: ["en"],
  // Carnatic kritis are sung in Telugu, Kannada, Sanskrit, and Tamil.
  carnatic: ["te", "kn", "sa", "ta"],
  // Hindustani khayal/bhajan repertoire is Hindi/Braj/Sanskrit-leaning.
  hindustani: ["hi", "sa"],
  "kannada-folk": ["kn"],
  // v1.3 Sprint 2: bhavageete is Kannada light-classical; Tamil folk
  // is Tamil janapada.
  "kannada-light-classical": ["kn"],
  "tamil-folk": ["ta"],
  // v1.4 Sprint 2 + 6: new families now have at least one PD source.
  "bollywood-ballad": ["hi"],
  "bengali-rabindrasangeet": ["bn"],
  // Tyagaraja kritis are Telugu but he also composed in Sanskrit.
  "telugu-keerthana": ["te", "sa"],
  // Shlokas are predominantly Sanskrit.
  "sanskrit-shloka": ["sa"],
};

function allowedLanguagesFor(styleFamily: StyleFamily): ReadonlySet<Language> {
  // Intersect domain preference with FS reality. Result: a style family's
  // allow-list automatically opens up when matching material is added on
  // disk, and the message a worker sees explains exactly what to add.
  const preference = STYLE_LANGUAGE_PREFERENCE[styleFamily];
  const present = new Set<Language>(BUNDLED_CORPUS_LANGUAGES);
  return new Set<Language>(preference.filter((l) => present.has(l)));
}

function findEntry(entries: LyricsEntry[], hint?: string): LyricsEntry {
  if (hint) {
    const normalisedHint = hint.toLowerCase();
    // 1. exact id match
    const byId = entries.find((e) => e.id.toLowerCase() === normalisedHint);
    if (byId) return byId;
    // 2. id ends with `<file>` (allow "tyger" -> "en/blake-tyger")
    const bySuffix = entries.find((e) =>
      e.id.toLowerCase().endsWith(`/${normalisedHint}`),
    );
    if (bySuffix) return bySuffix;
    // 3. title substring (case-insensitive)
    const byTitle = entries.find((e) =>
      e.title.toLowerCase().includes(normalisedHint),
    );
    if (byTitle) return byTitle;
  }
  // Deterministic fallback: first alphabetical entry. `loadCorpus` already
  // sorts.
  return entries[0]!;
}

export class PublicLyricsLibraryProvider implements LyricsProvider {
  readonly id = "public-library";
  private readonly corpusOpts: LoadCorpusOptions;

  constructor(options: PublicLyricsLibraryProviderOptions = {}) {
    this.corpusOpts = { rootDir: options.rootDir };
  }

  async generate(request: LyricsRequest): Promise<SongDocument> {
    const allowedLangs = allowedLanguagesFor(request.style_family);
    if (!allowedLangs.has(request.language)) {
      throw new Error(
        `PublicLyricsLibraryProvider: language=${request.language} is not ` +
          `paired with style_family=${request.style_family}. Allowed for ` +
          `${request.style_family}: ${[...allowedLangs].join(", ") || "(none on disk yet)"}.`,
      );
    }

    const entries = loadCorpus(request.language, this.corpusOpts);
    const entry = findEntry(entries, request.reference_lyrics ?? request.prompt);

    const sectionDrafts = mapToSections({
      body: entry.body,
      style_family: request.style_family,
      script: entry.script,
    });

    const scaffold = {
      language: request.language,
      style_family: request.style_family,
      target_duration_seconds: request.target_duration_seconds,
      sections: sectionDrafts,
      metadata: {
        // Provider-attribution lives under a namespace so a downstream
        // co-composer / producer cannot accidentally clobber it.
        neo_fm_lyrics_provider: {
          provider_id: this.id,
          entry_id: entry.id,
          entry_title: entry.title,
          entry_author: entry.author,
          entry_source_url: entry.source_url,
          entry_source_citation: entry.source_citation,
          entry_license: entry.license_assertion,
        },
      },
    };

    const allocated = allocateSectionDurations(scaffold);
    // Always go through schema.parse so a malformed corpus (e.g. an empty
    // body, an unrecognised script) becomes a clear error here instead of
    // arriving at the music-inference worker.
    return SongDocumentSchema.parse(allocated);
  }
}

/**
 * Pratyabhijna integration lands in Phase 10. Calling this earlier is a
 * deliberate runtime error so we never ship a silently-mocked creative
 * engine. The seam is kept so the cloud router doesn't have a hard branch
 * on phase-presence — it just instantiates the provider, the provider
 * throws, and the cloud reports a friendly "not yet integrated" error.
 */
export class PratyabhijnaProvider implements LyricsProvider {
  readonly id = "pratyabhijna";
  async generate(_request: LyricsRequest): Promise<SongDocument> {
    throw new NotYetIntegratedError("PratyabhijnaProvider", 10);
  }
}
