"""
Python pydantic v2 mirror of the canonical Zod-defined Song Document.

Structure: codegen + hand-written validators.

- `_generated.py` holds the data shapes (enums, BaseModel fields, scalar
  constraints) generated by `scripts/song-doc-codegen.py` from
  `packages/song-doc/song-doc.schema.json` (which is itself emitted from the
  Zod source of truth in `packages/song-doc/src/index.ts`). CI verifies that
  `_generated.py` matches the codegen output via the `--check` flag.
- This file adds cross-field validators that JSON Schema cannot express:
  - `raga.system` must match `style_family` for Carnatic / Hindustani.
  - `sum(section.target_seconds)` must equal `target_duration_seconds`.
- It also exports `allocate_section_durations()`, the Pydantic mirror of
  `allocateSectionDurations()` in the TS source.

Editing either of the codegen files by hand is a CI failure. Edit Zod, then
run `pnpm --filter @neo-fm/song-doc export-schema && python3 scripts/song-doc-codegen.py`.
"""

from __future__ import annotations

from typing import Any

from pydantic import model_validator

from . import _generated

Section = _generated.Section
Orchestration = _generated.Orchestration
RagaSpec = _generated.Raga

Language = _generated._SongDocumentBase.model_fields["language"].annotation
StyleFamily = _generated._SongDocumentBase.model_fields["style_family"].annotation
Duration = _generated._SongDocumentBase.model_fields["target_duration_seconds"].annotation
Script = Section.model_fields["script"].annotation
SectionType = Section.model_fields["type"].annotation


class SongDocument(_generated._SongDocumentBase):
    """Validated Song Document. Subclass of the codegen-only base; adds the
    invariants that JSON Schema cannot represent."""

    @model_validator(mode="after")
    def _raga_matches_style(self) -> SongDocument:
        if self.raga is None:
            return self
        raga_system = self.raga.system
        style = self.style_family
        match (raga_system, style):
            case ("carnatic", "carnatic") | ("hindustani", "hindustani"):
                pass
            case _:
                raise ValueError(
                    f'raga.system "{raga_system}" does not match style_family "{style}"'
                )
        return self

    @model_validator(mode="after")
    def _section_seconds_sum_matches_total(self) -> SongDocument:
        total = sum(s.target_seconds for s in self.sections)
        if total != self.target_duration_seconds:
            raise ValueError(
                f"sum(section.target_seconds) = {total} must equal "
                f"target_duration_seconds = {self.target_duration_seconds}; "
                "use allocate_section_durations() to auto-fill before validation"
            )
        return self


def allocate_section_durations(payload: dict[str, Any]) -> dict[str, Any]:
    """Mirror of `allocateSectionDurations()` in the TS source.

    Fills any `target_seconds` left unset across `payload['sections']` by
    splitting `payload['target_duration_seconds']` equally over the unset
    slots. Returns a new dict — the input is not mutated. The result is
    *not yet validated*; pipe it through `SongDocument.model_validate()`.
    """
    sections_in: list[dict[str, Any]] = list(payload.get("sections", []))
    total = int(payload["target_duration_seconds"])
    fixed_sum = sum(int(s["target_seconds"]) for s in sections_in if "target_seconds" in s)
    unset = [s for s in sections_in if "target_seconds" not in s]
    remaining = total - fixed_sum
    if remaining < 0:
        raise ValueError(
            f"fixed sections already consume {fixed_sum}s, exceeds "
            f"target_duration_seconds = {total}"
        )
    if not unset and remaining != 0:
        raise ValueError(
            f"all section.target_seconds set but sum = {fixed_sum} != "
            f"target_duration_seconds = {total}"
        )
    sections_out: list[dict[str, Any]] = []
    if unset:
        per, extra = divmod(remaining, len(unset))
        # Reject before allocating: a remainder that yields any zero-second
        # section would later fail SongDocument validation with a confusing
        # "target_seconds >= 1" message. Fail here with a clear one.
        if per == 0 and extra < len(unset):
            raise ValueError(
                f"allocate_section_durations cannot fit {len(unset)} unset "
                f"section(s) into {remaining}s remaining without producing "
                "a 0-second section. Reduce the number of unset sections or "
                "raise target_duration_seconds."
            )
        i = 0
        for s in sections_in:
            if "target_seconds" in s:
                sections_out.append(dict(s))
            else:
                share = per + (1 if i < extra else 0)
                sections_out.append({**s, "target_seconds": share})
                i += 1
    else:
        sections_out = [dict(s) for s in sections_in]
    return {**payload, "sections": sections_out}


class NotYetIntegratedError(RuntimeError):
    """Raised when a planned-but-deferred component is reached at runtime."""

    def __init__(self, component: str, phase: int) -> None:
        super().__init__(
            f"{component} integration lands in Phase {phase}; not wired yet."
        )
        self.component = component
        self.phase = phase
