#!/usr/bin/env tsx
/**
 * Generate `src/bundled-corpus.ts` from the `data/public-lyrics/` markdown
 * corpus.
 *
 * Motivation: the runtime `loadCorpus()` reads from disk via `fs.readFileSync`,
 * which works in dev and CI but is fragile in serverless deploys (Vercel
 * lambda doesn't necessarily ship the `data/` directory next to
 * `packages/lyrics/dist/`). For the M2 "library picker" surface we need
 * read-only access to the curated lyrics in the browser-facing API. So
 * we bundle them at package-build time.
 *
 * Run once and commit the output. Add new lyrics to `data/public-lyrics/`
 * then `pnpm --filter @neo-fm/lyrics bundle:corpus` to regenerate.
 *
 * Determinism: entries are sorted by `${language}/${id}` so the file
 * round-trips identically across machines.
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseFrontmatter } from "../src/frontmatter.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..", "..", "..");
const CORPUS_ROOT = join(REPO_ROOT, "data", "public-lyrics");
const OUT_PATH = resolve(HERE, "..", "src", "bundled-corpus.ts");

const LANGUAGES = ["en", "hi", "kn"] as const;

type BundledEntry = {
  id: string;
  title: string;
  author: string;
  language: (typeof LANGUAGES)[number];
  script: string;
  body: string;
  source_url: string;
  source_citation: string;
  license_assertion: "public-domain";
};

function readEntry(filePath: string, language: BundledEntry["language"]): BundledEntry {
  const text = readFileSync(filePath, "utf-8");
  const { frontmatter, body } = parseFrontmatter(text);

  const requiredString = (key: string): string => {
    const v = frontmatter[key];
    if (typeof v !== "string" || v.length === 0) {
      throw new Error(`${filePath}: missing required string field ${key}`);
    }
    return v;
  };

  if (frontmatter.language !== language) {
    throw new Error(
      `${filePath}: frontmatter language=${String(frontmatter.language)} disagrees with directory language=${language}`,
    );
  }
  if (frontmatter.license_assertion !== "public-domain") {
    throw new Error(
      `${filePath}: license_assertion=${String(frontmatter.license_assertion)} is not "public-domain"`,
    );
  }

  const fileBase = filePath.split("/").pop()?.replace(/\.md$/, "") ?? "unknown";
  return {
    id: `${language}/${fileBase}`,
    title: requiredString("title"),
    author: requiredString("author"),
    language,
    script: requiredString("script"),
    body: body.trim(),
    source_url: requiredString("source_url"),
    source_citation: requiredString("source_citation"),
    license_assertion: "public-domain",
  };
}

function loadAll(): BundledEntry[] {
  const entries: BundledEntry[] = [];
  for (const lang of LANGUAGES) {
    const dir = join(CORPUS_ROOT, lang);
    const names = readdirSync(dir).sort();
    for (const name of names) {
      if (!name.endsWith(".md")) continue;
      const filePath = join(dir, name);
      if (!statSync(filePath).isFile()) continue;
      entries.push(readEntry(filePath, lang));
    }
  }
  entries.sort((a, b) => a.id.localeCompare(b.id));
  return entries;
}

function emit(entries: BundledEntry[]): string {
  const header = `/**
 * Auto-generated by \`packages/lyrics/scripts/bundle-corpus.ts\`. Do not
 * edit by hand. To regenerate after adding a lyric:
 *
 *   pnpm --filter @neo-fm/lyrics bundle:corpus
 *
 * The corpus is bundled (rather than loaded from disk at runtime) so the
 * Vercel-deployed web app can serve it without shipping the markdown
 * directory next to the function bundle. See
 * \`packages/lyrics/scripts/bundle-corpus.ts\` for the source-of-truth.
 *
 * Provenance enforcement still happens in CI via
 * \`scripts/verify-lyrics-provenance.py\`. This file is purely the data
 * mirror.
 */
import type { LyricsEntry } from "./corpus.js";\n\n`;

  const body = `export const BUNDLED_CORPUS: readonly LyricsEntry[] = ${JSON.stringify(entries, null, 2)} as const;\n\n`;

  const helpers = `export function bundledCorpusForLanguage(language: LyricsEntry["language"]): LyricsEntry[] {
  return BUNDLED_CORPUS.filter((e) => e.language === language);
}

export function findBundledLyric(id: string): LyricsEntry | undefined {
  return BUNDLED_CORPUS.find((e) => e.id === id);
}\n`;

  return header + body + helpers;
}

const entries = loadAll();
const out = emit(entries);
writeFileSync(OUT_PATH, out, "utf-8");
console.log(`Wrote ${entries.length} entries to ${OUT_PATH}`);
